### ISSUE TITLE
Admin portal keeps redirecting after login since keycloak 25

### ISSUE THREAD

**Issue by Sp0Q1** [p2-inc/phasetwo-admin-portal#152] opened 2024-07-03 20:06 UTC
**How to reproduce:**
1. Deploy a docker-compose installation with `image: quay.io/phasetwo/phasetwo-keycloak:25.0.1.1718907377`
2. From a clean installation, create a new realm.
3. Create a new user in that realm and set a password.
4. Create a new organization in that realm.
5. Give user all privileges within organization.
6. Open new anonymous tab/browser and go to https://<KEYCLOAK_PATH>/realms/master/portal/ 
7. Log in with new user
8. Wait for page to refresh...
9. End up with a HTTP ERROR 431 because request URL got too big.

**More details**
The following requests are repeated (along with some other static files) until the HTTP 431:
```
https://<KEYCLOAK_PATH>/realms/master/portal/organizations
https://<KEYCLOAK_PATH>/realms/master/protocol/openid-connect/token
https://<KEYCLOAK_PATH>/realms/master/protocol/openid-connect/auth?client_id=admin-portal&redirect_uri=https%3A%2F%2F<KEYCLOAK_PATH>%2Frealms%2Fmaster%2Fportal%2Forganizations%23iss%3Dhttps%253A%252F%252F<KEYCLOAK_PATH>%252Frealms%252Fmaster%26iss%3Dhttps%253A%252F%252F<KEYCLOAK_PATH>%252Frealms%252Fmaster%26iss%3Dhttps%253A%252F%252F...
```

**Expected behaviour:**
1. Change `image: quay.io/phasetwo/phasetwo-keycloak:25.0.1.1718907377` to `image: quay.io/phasetwo/phasetwo-keycloak:24` in the docker-compose file.
2. Do everything above, but get a nice HTTP STATUS 200 with the admin portal.

**Comment by xgp** [comment] 2024-07-03 20:11
@pnzrr this and idp-wizard need to have `keycloak-js` upgraded to `25.0.1`

**Comment by vgallegob** [comment] 2024-07-04 00:11
same here, infinite redirects.


https://auth2.abc.io/realms/master/portal/organizations#iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.abc.io%2Frealms%2Fmaster&iss=https%3A%2F%2Fauth2.t

Is it necesary to have the /auth prefix? I didn't set that up

I tried going back from 25 to 24 but not the adminconsole wont load

**Comment by Sp0Q1** [comment] 2024-07-04 07:34
It's already fixed over here: https://github.com/p2-inc/phasetwo-admin-portal/pull/153

**Comment by xgp** [comment] 2024-07-04 07:39
fixed in `25.0.1.1720077951`

**Comment by Sp0Q1** [comment] 2024-07-04 07:39
thanks so much! This was really quick.

**Closed by xgp** 2024-07-04 07:39 UTC

**Comment by Sp0Q1** [comment] 2024-07-04 07:50
@xgp @pnzrr not sure if related, but I just tested the new version and while the redirection issue seems to be resolved, I cannot get access to the idp-wizard. It redirects me to "https://<domain>/auth/realms/<realm>/wizardaccess-denied" and throws a 404 there.

**Comment by xgp** [comment] 2024-07-04 08:04
@Sp0Q1 Can you check to see if the roles are in the token that it gets?

**Comment by Sp0Q1** [comment] 2024-07-04 08:05
yes, checking now.

**Comment by Sp0Q1** [comment] 2024-07-04 08:12
Not sure if this is what you mean, but this is the (slightly redacted) data in the access token that is requested when browsing to the idp wizard:
```
{
  "exp": 1720080707,
  "iat": 1720080407,
  "jti": "<snip/>",
  "iss": "https://<domain>/auth/realms/<realm>",
  "aud": "account",
  "sub": "<snip/>",
  "typ": "Bearer",
  "azp": "idp-wizard",
  "sid": "<snip/>",
  "acr": "0",
  "allowed-origins": [
    "/*"
  ],
  "realm_access": {
    "roles": [
      "default-roles-<realm>",
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid email profile",
  "email_verified": true,
  "name": "firstname lastname",
  "organizations": {
    "<snip/>": {
      "roles": [
        "view-organization",
        "manage-organization",
        "view-members",
        "manage-members",
        "view-roles",
        "manage-roles",
        "view-invitations",
        "manage-invitations",
        "view-identity-providers",
        "manage-identity-providers"
      ],
      "name": "<realm>"
    }
  },
  "preferred_username": "firstname",
  "given_name": "firstname",
  "locale": "nl",
  "family_name": "lastname",
  "email": "firstname@domain"
}
```

This was in the `access_token` in the response of the `/auth/realms/<realm>/protocol/openid-connect/token` POST request.

**Comment by Sp0Q1** [comment] 2024-07-04 08:12
This was again a newly setup instance, will do some more checks now.

**Comment by xgp** [comment] 2024-07-04 08:16
@Sp0Q1 It looks right. I'm able to reproduce.

@pnzrr under what conditions do we redirect to the access denied? The token call is succeeding with the correct content.
![image](https://github.com/p2-inc/phasetwo-admin-portal/assets/244253/d818bc32-9704-4b9a-a5e6-e0c323eeab5e)

**Comment by xgp** [comment] 2024-07-04 08:44
@pnzrr I think it might be in the logic of hasRealmRole/useRoleAccess that could have changed behavior in the `25` upgrade.

**Comment by vgallegob** [comment] 2024-07-04 10:34
It works now thanks!

**Comment by xgp** [comment] 2024-07-04 12:47
@pnzrr Looks like some difference/problem in loading the permissions. That hook eventually loads a `true`, but tries a few times.
![image](https://github.com/p2-inc/phasetwo-admin-portal/assets/244253/ba971add-0c8d-4bbf-b1d5-f0177ec989ef)

**Comment by pnzrr** [comment] 2024-07-04 14:28
@Sp0Q1 @xgp taking a look now. I think you're correct that there is a loading aspect waiting for roles to populate and since it still is it is prematurely trying to route to access-denied. I may have to tweak this to render a component rather than a redirect.
